#!/bin/bash

autorandr_dir=$(dirname "${AUTORANDR_PROFILE_FOLDER}")
current_profile_file="${autorandr_dir}/current"
if [[ -f "${current_profile_file}" ]]; then
  current_profile=$(cat "${current_profile_file}")
else
  current_profile='default'
fi
current_profile_dir="${autorandr_dir}/${current_profile}"
i3-msg -t get_workspaces > "${current_profile_dir}/window_config"
echo "Saving ${current_profile_dir}/window_config"
echo "${AUTORANDR_CURRENT_PROFILE}" > "${current_profile_file}"
