#!/bin/bash

set -eo pipefail

USAGE="Usage: $0 (up|down|status|help) [connection]"

if [ "$#" != "2" ]; then
	echo "$USAGE"
	exit 1
fi

case "$1" in
'up')
  # Do nothing
  ;;
'down')
  # Do nothing
  ;;
'status')
  echo "down"
  ;;
'help')
  echo "$USAGE"
  exit 1
  ;;
esac
